using bangna_hospital.control;
using C1.Win.C1Input;
using C1.Win.C1Themes;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;

namespace bangna_hospital.gui
{
    public class FrmOrOperativeNote:Form
    {
        BangnaControl bc;
        Font fEdit, fEditB, fEdit1;

        Label lbTitle, lbDept, lbWard, lbDtrId, lbDtrName, lbPttid, lbPttName, lbDateOperative, lbTimeInsion, lbTimeFinish, lbTotalTime, lbSurgeon, lbSurgeon1, lbSurgeon2, lbSurgeon3, lbSurgeon4;
        Label lbSurgeonName1, lbSurgeonName2, lbSurgeonName3, lbSurgeonName4, lbAssistant, lbAssistant1, lbAssistant2, lbAssistant3, lbAssistant4, lbAssistantName1, lbAssistantName2, lbAssistantName3, lbAssistantName4;
        Label lbScrubNurse, lbScrubNurse1, lbScrubNurseName1, lbScrubNurse2, lbScrubNurseName2, lbScrubNurse3, lbScrubNurseName3, lbScrubNurse4, lbScrubNurseName4;
        Label lbCircuNurse, lbCircuNurse1, lbCircuNurseName1, lbCircuNurse2, lbCircuNurseName2, lbCircuNurse3, lbCircuNurseName3, lbCircuNurse4, lbCircuNurseName4;
        C1TextBox txtDept, txtWard, txtDtrId, txtDtrname, txtTimeInsion, txtTimeFinish, txtTotalTime, txtSurgeon1, txtSurgeon2, txtSurgeon3, txtSurgeon4, txtAssistant1, txtAssistant2, txtAssistant3, txtAssistant4;
        C1TextBox txtScrubNurse1, txtScrubNurse2, txtScrubNurse3, txtScrubNurse4;
        C1TextBox txtCircuNurse1, txtCircuNurse2, txtCircuNurse3, txtCircuNurse4;
        Label lbPerfusionist, lbPerfusionist1, lbPerfusionistName1, lbPerfusionist2, lbPerfusionistName2;
        C1TextBox txtPerfusionist1, txtPerfusionist2;
        Label lbAnesthetist, lbAnesthetist1, lbAnesthetistName1;
        C1TextBox txtAnesthetist1;
        Label lbAnesthetistAssist, lbAnesthetistAssist1, lbAnesthetistAssistName1;
        C1TextBox txtAnesthetistAssist1;
        Label lbTimeAnthe, lbTimeFinishAnthe, lbTotalTimeAnthe;
        C1TextBox txtTimeAnthe, txtTimeFinishAnthe, txtTotalTimeAnthe;

        Label lbAnesthetistTechni;
        C1TextBox txtAnesthetistTechni1;
        Label lbPreOperation;
        C1TextBox txtPreOperation;
        Label lbPostOperation;
        C1TextBox txtPostOperation;
        Label lbOperation1, lbOperation2, lbOperation3, lbOperation4;
        C1TextBox txtOperation1, txtOperation2, txtOperation3, txtOperation4;

        Label lbFinding;
        C1TextBox txtFinding;

        C1Button btnPttSearch;
        C1DateEdit txtDateOperative;
        RadioButton chkOPD, chkIPD;
        Panel pnOperative, pnProcidures;
        C1ThemeController theme1;

        [DllImport("winspool.drv", CharSet = CharSet.Auto, SetLastError = true)]
        public static extern bool SetDefaultPrinter(string Printer);
        public FrmOrOperativeNote(BangnaControl bc)
        {
            this.bc = bc;
            initConfig();
        }
        private void initConfig()
        {
            fEdit = new Font(bc.iniC.grdViewFontName, bc.grdViewFontSize, FontStyle.Regular);
            fEditB = new Font(bc.iniC.grdViewFontName, bc.grdViewFontSize, FontStyle.Bold);
            fEdit1 = new Font(bc.iniC.grdViewFontName, bc.grdViewFontSize + 2, FontStyle.Regular);
            theme1 = new C1.Win.C1Themes.C1ThemeController();
            initCompoment();
            
            this.Load += FrmOrOperativeNote_Load;
        }
        
        private void initCompoment()
        {
            int gapLine = 30, gapX = 20, gapY = 20, xCol2=130, xCol1=80,xCol3=370, xCol4=700, xCol5=1030;
            Size size = new Size();
            int scrW = Screen.PrimaryScreen.Bounds.Width;
            int scrH = Screen.PrimaryScreen.Bounds.Height;

            pnOperative = new Panel();

            this.SuspendLayout();
            pnOperative.SuspendLayout();

            pnOperative.Dock = DockStyle.Fill;
            pnOperative.Name = "pnOperative";

            lbTitle = new Label();
            lbTitle.Text = "Operative Note ";
            lbTitle.Font = fEdit;
            size = bc.MeasureString(lbTitle);
            lbTitle.Location = new System.Drawing.Point(gapX, (scrW/2) + (size.Width /2));
            lbTitle.AutoSize = true;

            gapY += gapLine;

            lbDept = new Label();
            lbDept.Text = "Department :";
            lbDept.Font = fEdit;
            lbDept.Location = new System.Drawing.Point(gapX, gapY);
            lbDept.AutoSize = true;
            size = bc.MeasureString(lbDept);
            txtDept = new C1TextBox();
            txtDept.Font = fEdit;
            txtDept.Location = new System.Drawing.Point(xCol2, lbDept.Location.Y);
            txtDept.Size = new Size(120, 30);

            lbWard = new Label();
            lbWard.Text = "Ward :";
            lbWard.Font = fEdit;
            lbWard.Location = new System.Drawing.Point(txtDept.Location.X + txtDept.Width + 15, lbDept.Location.Y);
            lbWard.AutoSize = true;
            size = bc.MeasureString(lbWard);
            txtWard = new C1TextBox();
            txtWard.Font = fEdit;
            txtWard.Location = new System.Drawing.Point(lbWard.Location.X + size.Width + 5, lbDept.Location.Y);
            txtWard.Size = new Size(120, 30);

            lbDtrId = new Label();
            lbDtrId.Text = "Attending Staff :";
            lbDtrId.Font = fEdit;
            lbDtrId.Location = new System.Drawing.Point(txtWard.Location.X + txtWard.Width + 15, lbDept.Location.Y);
            lbDtrId.AutoSize = true;
            size = bc.MeasureString(lbDtrId);
            txtDtrId = new C1TextBox();
            txtDtrId.Font = fEdit;
            txtDtrId.Location = new System.Drawing.Point(lbDtrId.Location.X + size.Width + 5, lbDept.Location.Y);
            txtDtrId.Size = new Size(100, 30);
            lbDtrName = new Label();
            lbDtrName.Text = "...";
            lbDtrName.Font = fEdit;
            lbDtrName.Location = new System.Drawing.Point(txtDtrId.Location.X + txtDtrId.Width + 5, gapY);
            lbDtrName.AutoSize = true;

            gapY += gapLine;
            lbPttid = new Label();
            lbPttid.Text = "Patient :";
            lbPttid.Font = fEdit;
            lbPttid.Location = new System.Drawing.Point(gapX, gapY);
            lbPttid.AutoSize = true;
            size = bc.MeasureString(lbPttid);
            btnPttSearch = new C1Button();
            btnPttSearch.Name = "btnPttSearch";
            btnPttSearch.Text = "...";
            btnPttSearch.Font = fEdit;
            btnPttSearch.Location = new System.Drawing.Point(lbPttid.Location.X + size.Width, lbPttid.Location.Y);
            btnPttSearch.Size = new Size(30, 25);
            btnPttSearch.Font = fEdit;
            size = bc.MeasureString(btnPttSearch);
            lbPttName = new Label();
            lbPttName.Text = "...";
            lbPttName.Font = fEdit1;
            lbPttName.Location = new System.Drawing.Point(btnPttSearch.Location.X + btnPttSearch.Width + 5, gapY);
            lbPttName.AutoSize = true;

            gapY += gapLine;
            lbDateOperative = new Label();
            lbDateOperative.Text = "Date of Operative :";
            lbDateOperative.Font = fEdit;
            lbDateOperative.Location = new System.Drawing.Point(gapX, gapY);
            lbDateOperative.AutoSize = true;
            txtDateOperative = new C1DateEdit();
            txtDateOperative.AllowSpinLoop = false;
            txtDateOperative.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtDateOperative.Calendar.Font = new System.Drawing.Font("Tahoma", 8F);
            txtDateOperative.Calendar.VisualStyle = C1.Win.C1Input.VisualStyle.Office2007Blue;
            txtDateOperative.Calendar.VisualStyleBaseStyle = C1.Win.C1Input.VisualStyle.Office2007Blue;
            txtDateOperative.CurrentTimeZone = false;
            txtDateOperative.DisplayFormat.CustomFormat = "dd/MM/yyyy";
            txtDateOperative.DisplayFormat.FormatType = C1.Win.C1Input.FormatTypeEnum.CustomFormat;
            txtDateOperative.DisplayFormat.Inherit = ((C1.Win.C1Input.FormatInfoInheritFlags)(((((C1.Win.C1Input.FormatInfoInheritFlags.NullText | C1.Win.C1Input.FormatInfoInheritFlags.EmptyAsNull)
            | C1.Win.C1Input.FormatInfoInheritFlags.TrimStart)
            | C1.Win.C1Input.FormatInfoInheritFlags.TrimEnd)
            | C1.Win.C1Input.FormatInfoInheritFlags.CalendarType)));
            txtDateOperative.EditFormat.CustomFormat = "dd/MM/yyyy";
            txtDateOperative.EditFormat.FormatType = C1.Win.C1Input.FormatTypeEnum.CustomFormat;
            txtDateOperative.EditFormat.Inherit = ((C1.Win.C1Input.FormatInfoInheritFlags)(((((C1.Win.C1Input.FormatInfoInheritFlags.NullText | C1.Win.C1Input.FormatInfoInheritFlags.EmptyAsNull)
            | C1.Win.C1Input.FormatInfoInheritFlags.TrimStart)
            | C1.Win.C1Input.FormatInfoInheritFlags.TrimEnd)
            | C1.Win.C1Input.FormatInfoInheritFlags.CalendarType)));
            txtDateOperative.Font = new System.Drawing.Font("Microsoft Sans Serif", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            txtDateOperative.GMTOffset = System.TimeSpan.Parse("00:00:00");
            txtDateOperative.ImagePadding = new System.Windows.Forms.Padding(0);
            size = bc.MeasureString(lbDateOperative);
            txtDateOperative.Location = new System.Drawing.Point(lbDateOperative.Location.X + size.Width + 15, lbDateOperative.Location.Y);
            txtDateOperative.Name = "txtDateOperative";
            txtDateOperative.Size = new System.Drawing.Size(150, 20);
            txtDateOperative.TabIndex = 12;
            txtDateOperative.Tag = null;
            theme1.SetTheme(this.txtDateOperative, "(default)");
            txtDateOperative.VisualStyle = C1.Win.C1Input.VisualStyle.Office2007Blue;
            txtDateOperative.VisualStyleBaseStyle = C1.Win.C1Input.VisualStyle.Office2007Blue;

            lbTimeInsion = new Label();
            lbTimeInsion.Text = "Insion Time :";
            lbTimeInsion.Font = fEdit;
            lbTimeInsion.Location = new System.Drawing.Point(txtDateOperative.Location.X + txtDateOperative.Width + 15, lbDateOperative.Location.Y);
            lbTimeInsion.AutoSize = true;
            size = bc.MeasureString(lbTimeInsion);
            txtTimeInsion = new C1TextBox();
            txtTimeInsion.Font = fEdit;
            txtTimeInsion.Location = new System.Drawing.Point(lbTimeInsion.Location.X + size.Width + 5, lbDateOperative.Location.Y);
            txtTimeInsion.Size = new Size(80, 30);
            lbTimeFinish = new Label();
            lbTimeFinish.Text = "Finish Time :";
            lbTimeFinish.Font = fEdit;
            lbTimeFinish.Location = new System.Drawing.Point(txtTimeInsion.Location.X + txtTimeInsion.Width + 15, lbDateOperative.Location.Y);
            lbTimeFinish.AutoSize = true;
            size = bc.MeasureString(lbTimeFinish);
            txtTimeFinish = new C1TextBox();
            txtTimeFinish.Font = fEdit;
            txtTimeFinish.Location = new System.Drawing.Point(lbTimeFinish.Location.X + size.Width + 5, lbDateOperative.Location.Y);
            txtTimeFinish.Size = new Size(80, 30);
            lbTotalTime = new Label();
            lbTotalTime.Text = "Total Time :";
            lbTotalTime.Font = fEdit;
            lbTotalTime.Location = new System.Drawing.Point(txtTimeFinish.Location.X + txtTimeFinish.Width + 15, lbDateOperative.Location.Y);
            lbTotalTime.AutoSize = true;
            size = bc.MeasureString(lbTotalTime);
            txtTotalTime = new C1TextBox();
            txtTotalTime.Font = fEdit;
            txtTotalTime.Location = new System.Drawing.Point(lbTotalTime.Location.X + size.Width + 5, lbDateOperative.Location.Y);
            txtTotalTime.Size = new Size(80, 30);
            txtTotalTime.Name = "txtTotalTime";

            gapY += gapLine;
            gapY += gapLine;
            lbSurgeon = new Label();
            lbSurgeon.Text = "Surgeon ";
            lbSurgeon.Font = fEdit;
            lbSurgeon.Location = new System.Drawing.Point(gapX, gapY);
            lbSurgeon.AutoSize = true;
            //size = bc.MeasureString(lbSurgeon);
            gapY += gapLine;
            lbSurgeon1 = new Label();
            lbSurgeon1.Text = "1 :";
            lbSurgeon1.Font = fEdit;
            lbSurgeon1.Location = new System.Drawing.Point(gapX, gapY);
            lbSurgeon1.AutoSize = true;
            size = bc.MeasureString(lbSurgeon1);
            txtSurgeon1 = new C1TextBox();
            txtSurgeon1.Font = fEdit;
            txtSurgeon1.Location = new System.Drawing.Point(lbSurgeon1.Location.X + size.Width + 5, lbSurgeon1.Location.Y);
            txtSurgeon1.Size = new Size(80, 30);
            txtSurgeon1.Name = "txtSurgeon1";
            lbSurgeonName1 = new Label();
            lbSurgeonName1.Text = "...";
            lbSurgeonName1.Font = fEdit;
            lbSurgeonName1.Location = new System.Drawing.Point(txtSurgeon1.Location.X + txtSurgeon1.Width + 15, lbSurgeon1.Location.Y);
            lbSurgeonName1.AutoSize = true;
            lbSurgeonName1.Name = "lbSurgeonName1";

            lbAssistant = new Label();
            lbAssistant.Text = "Assistant ";
            lbAssistant.Font = fEdit;
            lbAssistant.Location = new System.Drawing.Point(xCol3, lbSurgeon.Location.Y);
            lbAssistant.AutoSize = true;
            size = bc.MeasureString(lbAssistant);
            lbAssistant1 = new Label();
            lbAssistant1.Text = "1 :";
            lbAssistant1.Font = fEdit;
            lbAssistant1.Location = new System.Drawing.Point(xCol3, lbSurgeon1.Location.Y);
            lbAssistant1.AutoSize = true;
            size = bc.MeasureString(lbAssistant1);
            txtAssistant1 = new C1TextBox();
            txtAssistant1.Font = fEdit;
            txtAssistant1.Location = new System.Drawing.Point(lbAssistant1.Location.X + size.Width + 5, lbSurgeon1.Location.Y);
            txtAssistant1.Size = new Size(80, 30);
            txtAssistant1.Name = "txtAssistant1";
            lbAssistantName1 = new Label();
            lbAssistantName1.Text = "...";
            lbAssistantName1.Font = fEdit;
            lbAssistantName1.Location = new System.Drawing.Point(txtAssistant1.Location.X + txtAssistant1.Width + 15, lbSurgeon1.Location.Y);
            lbAssistantName1.AutoSize = true;
            lbAssistantName1.Name = "lbAssistantName1";

            lbScrubNurse = new Label();
            lbScrubNurse.Text = "Scrub Nurse ";
            lbScrubNurse.Font = fEdit;
            lbScrubNurse.Location = new System.Drawing.Point(xCol4, lbSurgeon.Location.Y);
            lbScrubNurse.AutoSize = true;
            size = bc.MeasureString(lbScrubNurse);
            lbScrubNurse1 = new Label();
            lbScrubNurse1.Text = "1 :";
            lbScrubNurse1.Font = fEdit;
            lbScrubNurse1.Location = new System.Drawing.Point(xCol4, lbSurgeon1.Location.Y);
            lbScrubNurse1.AutoSize = true;
            size = bc.MeasureString(lbScrubNurse1);
            txtScrubNurse1 = new C1TextBox();
            txtScrubNurse1.Font = fEdit;
            txtScrubNurse1.Location = new System.Drawing.Point(lbScrubNurse1.Location.X + size.Width + 5, lbSurgeon1.Location.Y);
            txtScrubNurse1.Size = new Size(80, 30);
            txtScrubNurse1.Name = "txtScrubNurse1";
            lbScrubNurseName1 = new Label();
            lbScrubNurseName1.Text = "...";
            lbScrubNurseName1.Font = fEdit;
            lbScrubNurseName1.Location = new System.Drawing.Point(txtScrubNurse1.Location.X + txtScrubNurse1.Width + 15, lbSurgeon1.Location.Y);
            lbScrubNurseName1.AutoSize = true;
            lbScrubNurseName1.Name = "lbScrubNurseName1";

            lbCircuNurse = new Label();
            lbCircuNurse.Text = "Circulation Nurse ";
            lbCircuNurse.Font = fEdit;
            lbCircuNurse.Location = new System.Drawing.Point(xCol5, lbSurgeon.Location.Y);
            lbCircuNurse.AutoSize = true;
            size = bc.MeasureString(lbCircuNurse);
            lbCircuNurse1 = new Label();
            lbCircuNurse1.Text = "1 :";
            lbCircuNurse1.Font = fEdit;
            lbCircuNurse1.Location = new System.Drawing.Point(xCol5, lbSurgeon1.Location.Y);
            lbCircuNurse1.AutoSize = true;
            size = bc.MeasureString(lbCircuNurse1);
            txtCircuNurse1 = new C1TextBox();
            txtCircuNurse1.Font = fEdit;
            txtCircuNurse1.Location = new System.Drawing.Point(lbCircuNurse1.Location.X + size.Width + 5, lbSurgeon1.Location.Y);
            txtCircuNurse1.Size = new Size(80, 30);
            txtCircuNurse1.Name = "txtCircuNurse1";
            lbCircuNurseName1 = new Label();
            lbCircuNurseName1.Text = "...";
            lbCircuNurseName1.Font = fEdit;
            lbCircuNurseName1.Location = new System.Drawing.Point(txtCircuNurse1.Location.X + txtCircuNurse1.Width + 15, lbSurgeon1.Location.Y);
            lbCircuNurseName1.AutoSize = true;
            lbCircuNurseName1.Name = "lbCircuNurseName1";

            gapY += gapLine;
            lbSurgeon2 = new Label();
            lbSurgeon2.Text = "2 :";
            lbSurgeon2.Font = fEdit;
            lbSurgeon2.Location = new System.Drawing.Point(lbSurgeon1.Location.X, gapY);
            lbSurgeon2.AutoSize = true;
            lbSurgeon2.Name = "lbSurgeon2";
            size = bc.MeasureString(lbSurgeon2);
            txtSurgeon2 = new C1TextBox();
            txtSurgeon2.Font = fEdit;
            txtSurgeon2.Location = new System.Drawing.Point(lbSurgeon2.Location.X + size.Width + 5, lbSurgeon2.Location.Y);
            txtSurgeon2.Size = new Size(80, 30);
            txtSurgeon2.Name = "txtSurgeon2";
            lbSurgeonName2 = new Label();
            lbSurgeonName2.Text = "...";
            lbSurgeonName2.Font = fEdit;
            lbSurgeonName2.Location = new System.Drawing.Point(txtSurgeon2.Location.X + txtSurgeon2.Width + 15, lbSurgeon2.Location.Y);
            lbSurgeonName2.AutoSize = true;
            lbSurgeonName2.Name = "lbSurgeonName2";
            lbAssistant2 = new Label();
            lbAssistant2.Text = "2 :";
            lbAssistant2.Font = fEdit;
            lbAssistant2.Location = new System.Drawing.Point(lbAssistant1.Location.X , lbSurgeon2.Location.Y);
            lbAssistant2.AutoSize = true;
            size = bc.MeasureString(lbAssistant2);
            txtAssistant2 = new C1TextBox();
            txtAssistant2.Font = fEdit;
            txtAssistant2.Location = new System.Drawing.Point(lbAssistant2.Location.X + size.Width + 5, lbSurgeon2.Location.Y);
            txtAssistant2.Size = new Size(80, 30);
            txtAssistant2.Name = "txtAssistant2";
            lbAssistantName2 = new Label();
            lbAssistantName2.Text = "...";
            lbAssistantName2.Font = fEdit;
            lbAssistantName2.Location = new System.Drawing.Point(txtAssistant2.Location.X + txtAssistant2.Width + 15, lbSurgeon2.Location.Y);
            lbAssistantName2.AutoSize = true;
            lbAssistantName2.Name = "lbAssistantName2";

            lbScrubNurse2 = new Label();
            lbScrubNurse2.Text = "2 :";
            lbScrubNurse2.Font = fEdit;
            lbScrubNurse2.Location = new System.Drawing.Point(lbScrubNurse1.Location.X, lbSurgeon2.Location.Y);
            lbScrubNurse2.AutoSize = true;
            size = bc.MeasureString(lbScrubNurse2);
            txtScrubNurse2 = new C1TextBox();
            txtScrubNurse2.Font = fEdit;
            txtScrubNurse2.Location = new System.Drawing.Point(lbScrubNurse2.Location.X + size.Width + 5, lbSurgeon2.Location.Y);
            txtScrubNurse2.Size = new Size(80, 30);
            txtScrubNurse2.Name = "txtScrubNurse2";
            lbScrubNurseName2 = new Label();
            lbScrubNurseName2.Text = "...";
            lbScrubNurseName2.Font = fEdit;
            lbScrubNurseName2.Location = new System.Drawing.Point(txtScrubNurse2.Location.X + txtScrubNurse2.Width + 15, lbSurgeon2.Location.Y);
            lbScrubNurseName2.AutoSize = true;
            lbScrubNurseName2.Name = "lbScrubNurseName2";

            lbCircuNurse2 = new Label();
            lbCircuNurse2.Text = "1 :";
            lbCircuNurse2.Font = fEdit;
            lbCircuNurse2.Location = new System.Drawing.Point(xCol5, lbSurgeon2.Location.Y);
            lbCircuNurse2.AutoSize = true;
            size = bc.MeasureString(lbCircuNurse2);
            txtCircuNurse2 = new C1TextBox();
            txtCircuNurse2.Font = fEdit;
            txtCircuNurse2.Location = new System.Drawing.Point(lbCircuNurse2.Location.X + size.Width + 5, lbSurgeon2.Location.Y);
            txtCircuNurse2.Size = new Size(80, 30);
            txtCircuNurse2.Name = "txtCircuNurse2";
            lbCircuNurseName2 = new Label();
            lbCircuNurseName2.Text = "...";
            lbCircuNurseName2.Font = fEdit;
            lbCircuNurseName2.Location = new System.Drawing.Point(txtCircuNurse2.Location.X + txtCircuNurse2.Width + 15, lbSurgeon2.Location.Y);
            lbCircuNurseName2.AutoSize = true;
            lbCircuNurseName2.Name = "lbCircuNurseName2";

            gapY += gapLine;
            lbSurgeon3 = new Label();
            lbSurgeon3.Text = "3 :";
            lbSurgeon3.Font = fEdit;
            lbSurgeon3.Location = new System.Drawing.Point(lbSurgeon1.Location.X , gapY);
            lbSurgeon3.AutoSize = true;
            lbSurgeon3.Name = "lbSurgeon3";
            size = bc.MeasureString(lbSurgeon2);
            txtSurgeon3 = new C1TextBox();
            txtSurgeon3.Font = fEdit;
            txtSurgeon3.Location = new System.Drawing.Point(lbSurgeon3.Location.X + size.Width + 5, lbSurgeon3.Location.Y);
            txtSurgeon3.Size = new Size(80, 30);
            txtSurgeon3.Name = "txtSurgeon3";
            lbSurgeonName3 = new Label();
            lbSurgeonName3.Text = "...";
            lbSurgeonName3.Font = fEdit;
            lbSurgeonName3.Location = new System.Drawing.Point(txtSurgeon3.Location.X + txtSurgeon3.Width + 15, lbSurgeon3.Location.Y);
            lbSurgeonName3.AutoSize = true;
            lbSurgeonName3.Name = "lbSurgeonName3";
            lbAssistant3 = new Label();
            lbAssistant3.Text = "3 :";
            lbAssistant3.Font = fEdit;
            lbAssistant3.Location = new System.Drawing.Point(lbAssistant1.Location.X, lbSurgeon3.Location.Y);
            lbAssistant3.AutoSize = true;
            size = bc.MeasureString(lbAssistant3);
            txtAssistant3 = new C1TextBox();
            txtAssistant3.Font = fEdit;
            txtAssistant3.Location = new System.Drawing.Point(lbAssistant3.Location.X + size.Width + 5, lbSurgeon3.Location.Y);
            txtAssistant3.Size = new Size(80, 30);
            txtAssistant3.Name = "txtAssistant3";
            lbAssistantName3 = new Label();
            lbAssistantName3.Text = "...";
            lbAssistantName3.Font = fEdit;
            lbAssistantName3.Location = new System.Drawing.Point(txtAssistant3.Location.X + txtAssistant3.Width + 15, lbSurgeon3.Location.Y);
            lbAssistantName3.AutoSize = true;
            lbAssistantName3.Name = "lbAssistantName3";

            lbScrubNurse3 = new Label();
            lbScrubNurse3.Text = "3 :";
            lbScrubNurse3.Font = fEdit;
            lbScrubNurse3.Location = new System.Drawing.Point(lbScrubNurse1.Location.X, lbSurgeon3.Location.Y);
            lbScrubNurse3.AutoSize = true;
            size = bc.MeasureString(lbScrubNurse3);
            txtScrubNurse3 = new C1TextBox();
            txtScrubNurse3.Font = fEdit;
            txtScrubNurse3.Location = new System.Drawing.Point(lbScrubNurse3.Location.X + size.Width + 5, lbSurgeon3.Location.Y);
            txtScrubNurse3.Size = new Size(80, 30);
            txtScrubNurse3.Name = "txtScrubNurse3";
            lbScrubNurseName3 = new Label();
            lbScrubNurseName3.Text = "...";
            lbScrubNurseName3.Font = fEdit;
            lbScrubNurseName3.Location = new System.Drawing.Point(txtScrubNurse3.Location.X + txtScrubNurse3.Width + 15, lbSurgeon3.Location.Y);
            lbScrubNurseName3.AutoSize = true;
            lbScrubNurseName3.Name = "lbScrubNurseName3";

            lbCircuNurse3 = new Label();
            lbCircuNurse3.Text = "3 :";
            lbCircuNurse3.Font = fEdit;
            lbCircuNurse3.Location = new System.Drawing.Point(xCol5, lbSurgeon3.Location.Y);
            lbCircuNurse3.AutoSize = true;
            size = bc.MeasureString(lbCircuNurse3);
            txtCircuNurse3 = new C1TextBox();
            txtCircuNurse3.Font = fEdit;
            txtCircuNurse3.Location = new System.Drawing.Point(lbCircuNurse3.Location.X + size.Width + 5, lbSurgeon3.Location.Y);
            txtCircuNurse3.Size = new Size(80, 30);
            txtCircuNurse3.Name = "txtCircuNurse3";
            lbCircuNurseName3 = new Label();
            lbCircuNurseName3.Text = "...";
            lbCircuNurseName3.Font = fEdit;
            lbCircuNurseName3.Location = new System.Drawing.Point(txtCircuNurse3.Location.X + txtCircuNurse3.Width + 15, lbSurgeon3.Location.Y);
            lbCircuNurseName3.AutoSize = true;
            lbCircuNurseName3.Name = "lbCircuNurseName3";

            gapY += gapLine;
            lbSurgeon4 = new Label();
            lbSurgeon4.Text = "4 :";
            lbSurgeon4.Font = fEdit;
            lbSurgeon4.Location = new System.Drawing.Point(lbSurgeon1.Location.X, gapY);
            lbSurgeon4.AutoSize = true;
            lbSurgeon4.Name = "lbSurgeon4";
            size = bc.MeasureString(lbSurgeon4);
            txtSurgeon4 = new C1TextBox();
            txtSurgeon4.Font = fEdit;
            txtSurgeon4.Location = new System.Drawing.Point(lbSurgeon4.Location.X + size.Width + 5, lbSurgeon4.Location.Y);
            txtSurgeon4.Size = new Size(80, 30);
            txtSurgeon4.Name = "txtSurgeon4";
            lbSurgeonName4 = new Label();
            lbSurgeonName4.Text = "...";
            lbSurgeonName4.Font = fEdit;
            lbSurgeonName4.Location = new System.Drawing.Point(txtSurgeon4.Location.X + txtSurgeon4.Width + 15, lbSurgeon4.Location.Y);
            lbSurgeonName4.AutoSize = true;
            lbSurgeonName4.Name = "lbSurgeonName4";
            lbAssistant4 = new Label();
            lbAssistant4.Text = "4 :";
            lbAssistant4.Font = fEdit;
            lbAssistant4.Location = new System.Drawing.Point(lbAssistant1.Location.X, lbSurgeon4.Location.Y);
            lbAssistant4.AutoSize = true;
            size = bc.MeasureString(lbAssistant4);
            txtAssistant4 = new C1TextBox();
            txtAssistant4.Font = fEdit;
            txtAssistant4.Location = new System.Drawing.Point(lbAssistant4.Location.X + size.Width + 5, lbSurgeon4.Location.Y);
            txtAssistant4.Size = new Size(80, 30);
            txtAssistant4.Name = "txtAssistant4";
            lbAssistantName4 = new Label();
            lbAssistantName4.Text = "...";
            lbAssistantName4.Font = fEdit;
            lbAssistantName4.Location = new System.Drawing.Point(txtAssistant4.Location.X + txtAssistant4.Width + 15, lbSurgeon4.Location.Y);
            lbAssistantName4.AutoSize = true;
            lbAssistantName4.Name = "lbAssistantName4";

            lbScrubNurse4 = new Label();
            lbScrubNurse4.Text = "4 :";
            lbScrubNurse4.Font = fEdit;
            lbScrubNurse4.Location = new System.Drawing.Point(lbScrubNurse1.Location.X, lbSurgeon4.Location.Y);
            lbScrubNurse4.AutoSize = true;
            size = bc.MeasureString(lbScrubNurse4);
            txtScrubNurse4 = new C1TextBox();
            txtScrubNurse4.Font = fEdit;
            txtScrubNurse4.Location = new System.Drawing.Point(lbScrubNurse4.Location.X + size.Width + 5, lbSurgeon4.Location.Y);
            txtScrubNurse4.Size = new Size(80, 30);
            txtScrubNurse4.Name = "txtScrubNurse4";
            lbScrubNurseName4 = new Label();
            lbScrubNurseName4.Text = "...";
            lbScrubNurseName4.Font = fEdit;
            lbScrubNurseName4.Location = new System.Drawing.Point(txtScrubNurse4.Location.X + txtScrubNurse4.Width + 15, lbSurgeon4.Location.Y);
            lbScrubNurseName4.AutoSize = true;
            lbScrubNurseName4.Name = "lbScrubNurseName4";

            lbCircuNurse4 = new Label();
            lbCircuNurse4.Text = "4 :";
            lbCircuNurse4.Font = fEdit;
            lbCircuNurse4.Location = new System.Drawing.Point(xCol5, lbSurgeon4.Location.Y);
            lbCircuNurse4.AutoSize = true;
            size = bc.MeasureString(lbCircuNurse4);
            txtCircuNurse4 = new C1TextBox();
            txtCircuNurse4.Font = fEdit;
            txtCircuNurse4.Location = new System.Drawing.Point(lbCircuNurse4.Location.X + size.Width + 5, lbSurgeon4.Location.Y);
            txtCircuNurse4.Size = new Size(80, 30);
            txtCircuNurse4.Name = "txtCircuNurse4";
            lbCircuNurseName4 = new Label();
            lbCircuNurseName4.Text = "...";
            lbCircuNurseName4.Font = fEdit;
            lbCircuNurseName4.Location = new System.Drawing.Point(txtCircuNurse4.Location.X + txtCircuNurse4.Width + 15, lbSurgeon4.Location.Y);
            lbCircuNurseName4.AutoSize = true;
            lbCircuNurseName4.Name = "lbCircuNurseName4";

            gapY += gapLine;
            lbPerfusionist = new Label();
            lbPerfusionist.Text = "Perfusionist ";
            lbPerfusionist.Font = fEdit;
            lbPerfusionist.Location = new System.Drawing.Point(gapX, gapY);
            lbPerfusionist.AutoSize = true;
            //size = bc.MeasureString(lbSurgeon);
            gapY += gapLine;
            lbPerfusionist1 = new Label();
            lbPerfusionist1.Text = "1 :";
            lbPerfusionist1.Font = fEdit;
            lbPerfusionist1.Location = new System.Drawing.Point(gapX, gapY);
            lbPerfusionist1.AutoSize = true;
            size = bc.MeasureString(lbPerfusionist1);
            txtPerfusionist1 = new C1TextBox();
            txtPerfusionist1.Font = fEdit;
            txtPerfusionist1.Location = new System.Drawing.Point(lbPerfusionist1.Location.X + size.Width + 5, lbPerfusionist1.Location.Y);
            txtPerfusionist1.Size = new Size(80, 30);
            txtPerfusionist1.Name = "txtPerfusionist1";
            lbPerfusionistName1 = new Label();
            lbPerfusionistName1.Text = "...";
            lbPerfusionistName1.Font = fEdit;
            lbPerfusionistName1.Location = new System.Drawing.Point(txtPerfusionist1.Location.X + txtPerfusionist1.Width + 15, lbPerfusionist1.Location.Y);
            lbPerfusionistName1.AutoSize = true;
            lbPerfusionistName1.Name = "lbPerfusionistName1";

            gapY += gapLine;
            lbPerfusionist2 = new Label();
            lbPerfusionist2.Text = "2 :";
            lbPerfusionist2.Font = fEdit;
            lbPerfusionist2.Location = new System.Drawing.Point(lbPerfusionist1.Location.X, gapY);
            lbPerfusionist2.AutoSize = true;
            lbPerfusionist2.Name = "lbPerfusionist2";
            size = bc.MeasureString(lbSurgeon2);
            txtPerfusionist2 = new C1TextBox();
            txtPerfusionist2.Font = fEdit;
            txtPerfusionist2.Location = new System.Drawing.Point(lbPerfusionist2.Location.X + size.Width + 5, lbPerfusionist2.Location.Y);
            txtPerfusionist2.Size = new Size(80, 30);
            txtPerfusionist2.Name = "txtPerfusionist2";
            lbPerfusionistName2 = new Label();
            lbPerfusionistName2.Text = "...";
            lbPerfusionistName2.Font = fEdit;
            lbPerfusionistName2.Location = new System.Drawing.Point(txtPerfusionist2.Location.X + txtPerfusionist2.Width + 15, lbPerfusionist2.Location.Y);
            lbPerfusionistName2.AutoSize = true;
            lbPerfusionistName2.Name = "lbPerfusionistName2";

            lbAnesthetist = new Label();
            lbAnesthetist.Text = "Anesthetist ";
            lbAnesthetist.Font = fEdit;
            lbAnesthetist.Location = new System.Drawing.Point(xCol3, lbPerfusionist.Location.Y);
            lbAnesthetist.AutoSize = true;
            size = bc.MeasureString(lbAnesthetist);
            lbAnesthetist1 = new Label();
            lbAnesthetist1.Text = "1 :";
            lbAnesthetist1.Font = fEdit;
            lbAnesthetist1.Location = new System.Drawing.Point(xCol3, lbPerfusionist1.Location.Y);
            lbAnesthetist1.AutoSize = true;
            size = bc.MeasureString(lbAnesthetist1);
            txtAnesthetist1 = new C1TextBox();
            txtAnesthetist1.Font = fEdit;
            txtAnesthetist1.Location = new System.Drawing.Point(lbAssistant1.Location.X + size.Width + 5, lbPerfusionist1.Location.Y);
            txtAnesthetist1.Size = new Size(80, 30);
            txtAnesthetist1.Name = "txtAnesthetist1";
            lbAnesthetistName1 = new Label();
            lbAnesthetistName1.Text = "...";
            lbAnesthetistName1.Font = fEdit;
            lbAnesthetistName1.Location = new System.Drawing.Point(txtAnesthetist1.Location.X + txtAnesthetist1.Width + 15, lbPerfusionist1.Location.Y);
            lbAnesthetistName1.AutoSize = true;
            lbAnesthetistName1.Name = "lbAnesthetistName1";

            lbAnesthetistAssist = new Label();
            lbAnesthetistAssist.Text = "Anesthetist assistant ";
            lbAnesthetistAssist.Font = fEdit;
            lbAnesthetistAssist.Location = new System.Drawing.Point(xCol4, lbPerfusionist.Location.Y);
            lbAnesthetistAssist.AutoSize = true;
            size = bc.MeasureString(lbAnesthetistAssist);
            lbAnesthetistAssist1 = new Label();
            lbAnesthetistAssist1.Text = "1 :";
            lbAnesthetistAssist1.Font = fEdit;
            lbAnesthetistAssist1.Location = new System.Drawing.Point(xCol4, lbPerfusionist1.Location.Y);
            lbAnesthetistAssist1.AutoSize = true;
            size = bc.MeasureString(lbAnesthetist1);
            txtAnesthetistAssist1 = new C1TextBox();
            txtAnesthetistAssist1.Font = fEdit;
            txtAnesthetistAssist1.Location = new System.Drawing.Point(lbAnesthetistAssist1.Location.X + size.Width + 5, lbPerfusionist1.Location.Y);
            txtAnesthetistAssist1.Size = new Size(80, 30);
            txtAnesthetistAssist1.Name = "txtAnesthetistAssist1";
            lbAnesthetistAssistName1 = new Label();
            lbAnesthetistAssistName1.Text = "...";
            lbAnesthetistAssistName1.Font = fEdit;
            lbAnesthetistAssistName1.Location = new System.Drawing.Point(txtAnesthetistAssist1.Location.X + txtAnesthetistAssist1.Width + 15, lbPerfusionist1.Location.Y);
            lbAnesthetistAssistName1.AutoSize = true;
            lbAnesthetistAssistName1.Name = "lbAnesthetistAssistName1";

            gapY += gapLine;
            lbAnesthetistTechni = new Label();
            lbAnesthetistTechni.Text = "Anesthetist Technique ";
            lbAnesthetistTechni.Font = fEdit;
            lbAnesthetistTechni.Location = new System.Drawing.Point(xCol3-200, gapY);
            lbAnesthetistTechni.AutoSize = true;
            
            size = bc.MeasureString(lbAnesthetistTechni);
            
            txtAnesthetistTechni1 = new C1TextBox();
            txtAnesthetistTechni1.Font = fEdit;
            txtAnesthetistTechni1.Location = new System.Drawing.Point(lbAnesthetistTechni.Location.X + size.Width + 5, lbAnesthetistTechni.Location.Y);
            txtAnesthetistTechni1.Size = new Size(300, 30);
            txtAnesthetistTechni1.Name = "txtAnesthetistTechni1";

            lbTimeAnthe = new Label();
            lbTimeAnthe.Text = "Anthesia Time :";
            lbTimeAnthe.Font = fEdit;
            lbTimeAnthe.Location = new System.Drawing.Point(txtAnesthetistTechni1.Location.X + txtAnesthetistTechni1.Width + 15, lbAnesthetistTechni.Location.Y);
            lbTimeAnthe.AutoSize = true;
            size = bc.MeasureString(lbTimeAnthe);
            txtTimeAnthe = new C1TextBox();
            txtTimeAnthe.Font = fEdit;
            txtTimeAnthe.Location = new System.Drawing.Point(lbTimeAnthe.Location.X + size.Width + 5, lbAnesthetistTechni.Location.Y);
            txtTimeAnthe.Size = new Size(80, 30);
            txtTimeAnthe.Name = "txtTimeAnthe";
            lbTimeFinishAnthe = new Label();
            lbTimeFinishAnthe.Text = "Finish :";
            lbTimeFinishAnthe.Font = fEdit;
            lbTimeFinishAnthe.Location = new System.Drawing.Point(txtTimeAnthe.Location.X + txtTimeAnthe.Width + 15, lbAnesthetistTechni.Location.Y);
            lbTimeFinishAnthe.AutoSize = true;
            size = bc.MeasureString(lbTimeFinishAnthe);
            txtTimeFinishAnthe = new C1TextBox();
            txtTimeFinishAnthe.Font = fEdit;
            txtTimeFinishAnthe.Location = new System.Drawing.Point(lbTimeFinishAnthe.Location.X + size.Width + 5, lbAnesthetistTechni.Location.Y);
            txtTimeFinishAnthe.Size = new Size(80, 30);
            txtTimeFinishAnthe.Name = "txtTimeFinishAnthe";
            lbTotalTimeAnthe = new Label();
            lbTotalTimeAnthe.Text = "Total :";
            lbTotalTimeAnthe.Font = fEdit;
            lbTotalTimeAnthe.Location = new System.Drawing.Point(txtTimeFinishAnthe.Location.X + txtTimeFinishAnthe.Width + 15, lbAnesthetistTechni.Location.Y);
            lbTotalTimeAnthe.AutoSize = true;
            size = bc.MeasureString(lbTotalTimeAnthe);
            txtTotalTimeAnthe = new C1TextBox();
            txtTotalTimeAnthe.Font = fEdit;
            txtTotalTimeAnthe.Location = new System.Drawing.Point(lbTotalTimeAnthe.Location.X + size.Width + 5, lbAnesthetistTechni.Location.Y);
            txtTotalTimeAnthe.Size = new Size(80, 30);
            txtTotalTimeAnthe.Name = "txtTotalTimeAnthe";

            gapY += gapLine;
            lbPreOperation = new Label();
            lbPreOperation.Text = "Pre Operation :";
            lbPreOperation.Font = fEdit;
            lbPreOperation.Location = new System.Drawing.Point(gapX, gapY);
            lbPreOperation.AutoSize = true;
            size = bc.MeasureString(lbPreOperation);
            txtPreOperation = new C1TextBox();
            txtPreOperation.Font = fEdit;
            txtPreOperation.Location = new System.Drawing.Point(txtDateOperative.Location.X , lbPreOperation.Location.Y);
            txtPreOperation.Size = new Size(300, 30);
            txtPreOperation.Name = "txtPreOperation";

            lbFinding = new Label();
            lbFinding.Text = "Finding :";
            lbFinding.Font = fEdit;
            lbFinding.Location = new System.Drawing.Point(xCol4, gapY);
            lbFinding.AutoSize = true;
            size = bc.MeasureString(lbFinding);
            txtFinding = new C1TextBox();
            txtFinding.Font = fEdit;
            txtFinding.Location = new System.Drawing.Point(lbFinding.Location.X + size.Width + 5, lbFinding.Location.Y);
            txtFinding.Size = new Size(300, 30);
            txtFinding.Name = "txtFinding";

            gapY += gapLine;
            lbPostOperation = new Label();
            lbPostOperation.Text = "Post Operation :";
            lbPostOperation.Font = fEdit;
            lbPostOperation.Location = new System.Drawing.Point(gapX, gapY);
            lbPostOperation.AutoSize = true;
            size = bc.MeasureString(lbPostOperation);
            txtPostOperation = new C1TextBox();
            txtPostOperation.Font = fEdit;
            txtPostOperation.Location = new System.Drawing.Point(txtDateOperative.Location.X , lbPostOperation.Location.Y);
            txtPostOperation.Size = new Size(300, 30);
            txtPostOperation.Name = "txtPostOperation";

            gapY += gapLine;
            lbOperation1 = new Label();
            lbOperation1.Text = "Operation1 :";
            lbOperation1.Font = fEdit;
            lbOperation1.Location = new System.Drawing.Point(gapX, gapY);
            lbOperation1.AutoSize = true;
            size = bc.MeasureString(lbOperation1);
            txtOperation1 = new C1TextBox();
            txtOperation1.Font = fEdit;
            txtOperation1.Location = new System.Drawing.Point(lbOperation1.Location.X + size.Width + 5, lbOperation1.Location.Y);
            txtOperation1.Size = new Size(300, 30);
            txtOperation1.Name = "txtOperation1";
            
            lbOperation3 = new Label();
            lbOperation3.Text = "Operation3 :";
            lbOperation3.Font = fEdit;
            lbOperation3.Location = new System.Drawing.Point(xCol4, gapY);
            lbOperation3.AutoSize = true;
            size = bc.MeasureString(lbOperation3);
            txtOperation3 = new C1TextBox();
            txtOperation3.Font = fEdit;
            txtOperation3.Location = new System.Drawing.Point(lbOperation3.Location.X + size.Width + 5, lbOperation3.Location.Y);
            txtOperation3.Size = new Size(300, 30);
            txtOperation3.Name = "txtOperation3";

            gapY += gapLine;
            lbOperation2 = new Label();
            lbOperation2.Text = "Operation2 :";
            lbOperation2.Font = fEdit;
            lbOperation2.Location = new System.Drawing.Point(gapX, gapY);
            lbOperation2.AutoSize = true;
            size = bc.MeasureString(lbOperation2);
            txtOperation2 = new C1TextBox();
            txtOperation2.Font = fEdit;
            txtOperation2.Location = new System.Drawing.Point(lbOperation2.Location.X + size.Width + 5, lbOperation2.Location.Y);
            txtOperation2.Size = new Size(300, 30);
            txtOperation2.Name = "txtOperation2";
            
            lbOperation4 = new Label();
            lbOperation4.Text = "Operation4 :";
            lbOperation4.Font = fEdit;
            lbOperation4.Location = new System.Drawing.Point(xCol4, gapY);
            lbOperation4.AutoSize = true;
            size = bc.MeasureString(lbOperation4);
            txtOperation4 = new C1TextBox();
            txtOperation4.Font = fEdit;
            txtOperation4.Location = new System.Drawing.Point(lbOperation4.Location.X + size.Width + 5, lbOperation4.Location.Y);
            txtOperation4.Size = new Size(300, 30);
            txtOperation4.Name = "txtOperation4";

            pnProcidures = new Panel();
            pnProcidures.Dock = DockStyle.Bottom;
            pnProcidures.Height = 300;
            pnProcidures.BackColor = Color.Red;

            FrmDoctorDiag1 frm = new FrmDoctorDiag1(bc,"Procidures","");
            frm.FormBorderStyle = FormBorderStyle.None;
            frm.TopLevel = false;
            frm.Dock = DockStyle.Fill;
            frm.AutoScroll = true;
            frm.Show();

            pnProcidures.Controls.Add(frm);
            pnOperative.Controls.Add(pnProcidures);
            pnOperative.Controls.Add(lbFinding);
            pnOperative.Controls.Add(txtFinding);

            pnOperative.Controls.Add(lbOperation1);
            pnOperative.Controls.Add(txtOperation1);
            pnOperative.Controls.Add(lbOperation2);
            pnOperative.Controls.Add(txtOperation2);
            pnOperative.Controls.Add(lbOperation3);
            pnOperative.Controls.Add(txtOperation3);
            pnOperative.Controls.Add(lbOperation4);
            pnOperative.Controls.Add(txtOperation4);

            pnOperative.Controls.Add(lbPreOperation);
            pnOperative.Controls.Add(txtPreOperation);
            pnOperative.Controls.Add(lbPostOperation);
            pnOperative.Controls.Add(txtPostOperation);

            pnOperative.Controls.Add(lbAnesthetistTechni);
            pnOperative.Controls.Add(txtAnesthetistTechni1);
            pnOperative.Controls.Add(lbTimeAnthe);
            pnOperative.Controls.Add(txtTimeAnthe);
            pnOperative.Controls.Add(lbTimeFinishAnthe);
            pnOperative.Controls.Add(txtTimeFinishAnthe);
            pnOperative.Controls.Add(lbTotalTimeAnthe);
            pnOperative.Controls.Add(txtTotalTimeAnthe);

            pnOperative.Controls.Add(lbAnesthetistAssist);
            pnOperative.Controls.Add(lbAnesthetistAssist1);
            pnOperative.Controls.Add(txtAnesthetistAssist1);
            pnOperative.Controls.Add(lbAnesthetistAssistName1);

            pnOperative.Controls.Add(lbAnesthetist);
            pnOperative.Controls.Add(lbAnesthetist1);
            pnOperative.Controls.Add(txtAnesthetist1);
            pnOperative.Controls.Add(lbAnesthetistName1);

            pnOperative.Controls.Add(lbPerfusionist);
            pnOperative.Controls.Add(lbPerfusionist1);
            pnOperative.Controls.Add(txtPerfusionist1);
            pnOperative.Controls.Add(lbPerfusionistName1);
            pnOperative.Controls.Add(lbPerfusionist2);
            pnOperative.Controls.Add(txtPerfusionist2);
            pnOperative.Controls.Add(lbPerfusionistName2);

            pnOperative.Controls.Add(lbPttName);
            pnOperative.Controls.Add(lbSurgeon);
            pnOperative.Controls.Add(lbSurgeon1);
            pnOperative.Controls.Add(txtSurgeon1);
            pnOperative.Controls.Add(lbSurgeonName1);
            pnOperative.Controls.Add(lbSurgeon2);
            pnOperative.Controls.Add(txtSurgeon2);
            pnOperative.Controls.Add(lbSurgeonName2);
            pnOperative.Controls.Add(lbSurgeon3);
            pnOperative.Controls.Add(txtSurgeon3);
            pnOperative.Controls.Add(lbSurgeonName3);
            pnOperative.Controls.Add(lbSurgeon4);
            pnOperative.Controls.Add(txtSurgeon4);
            pnOperative.Controls.Add(lbSurgeonName4);
            pnOperative.Controls.Add(lbAssistant);
            pnOperative.Controls.Add(lbAssistant1);
            pnOperative.Controls.Add(txtAssistant1);
            pnOperative.Controls.Add(lbAssistantName1);
            pnOperative.Controls.Add(lbAssistant2);
            pnOperative.Controls.Add(txtAssistant2);
            pnOperative.Controls.Add(lbAssistantName2);
            pnOperative.Controls.Add(lbAssistant3);
            pnOperative.Controls.Add(txtAssistant3);
            pnOperative.Controls.Add(lbAssistantName3);
            pnOperative.Controls.Add(lbAssistant4);
            pnOperative.Controls.Add(txtAssistant4);
            pnOperative.Controls.Add(lbAssistantName4);
            pnOperative.Controls.Add(lbScrubNurse);
            pnOperative.Controls.Add(lbScrubNurse1);
            pnOperative.Controls.Add(txtScrubNurse1);
            pnOperative.Controls.Add(lbScrubNurseName1);
            pnOperative.Controls.Add(lbScrubNurse2);
            pnOperative.Controls.Add(txtScrubNurse2);
            pnOperative.Controls.Add(lbScrubNurseName2);
            pnOperative.Controls.Add(lbScrubNurse3);
            pnOperative.Controls.Add(txtScrubNurse3);
            pnOperative.Controls.Add(lbScrubNurseName3);
            pnOperative.Controls.Add(lbScrubNurse4);
            pnOperative.Controls.Add(txtScrubNurse4);
            pnOperative.Controls.Add(lbScrubNurseName4);
            pnOperative.Controls.Add(lbCircuNurse);
            pnOperative.Controls.Add(lbCircuNurse1);
            pnOperative.Controls.Add(txtCircuNurse1);
            pnOperative.Controls.Add(lbCircuNurseName1);
            pnOperative.Controls.Add(lbCircuNurse2);
            pnOperative.Controls.Add(txtCircuNurse2);
            pnOperative.Controls.Add(lbCircuNurseName2);
            pnOperative.Controls.Add(lbCircuNurse3);
            pnOperative.Controls.Add(txtCircuNurse3);
            pnOperative.Controls.Add(lbCircuNurseName3);
            pnOperative.Controls.Add(lbCircuNurse4);
            pnOperative.Controls.Add(txtCircuNurse4);
            pnOperative.Controls.Add(lbCircuNurseName4);

            pnOperative.Controls.Add(lbTotalTime);
            pnOperative.Controls.Add(txtTotalTime);
            pnOperative.Controls.Add(lbTimeFinish);
            pnOperative.Controls.Add(txtTimeFinish);
            pnOperative.Controls.Add(lbTimeInsion);
            pnOperative.Controls.Add(txtTimeInsion);
            pnOperative.Controls.Add(lbDateOperative);
            pnOperative.Controls.Add(txtDateOperative);
            //pnOperative.Controls.Add(lbDtrName);

            pnOperative.Controls.Add(lbPttid);
            pnOperative.Controls.Add(btnPttSearch);
            pnOperative.Controls.Add(lbDtrName);

            pnOperative.Controls.Add(lbTitle);
            pnOperative.Controls.Add(lbDept);
            pnOperative.Controls.Add(lbWard);
            pnOperative.Controls.Add(lbDtrId);
            pnOperative.Controls.Add(txtWard);
            pnOperative.Controls.Add(txtDept);
            pnOperative.Controls.Add(txtDtrId);
            this.Controls.Add(pnOperative);

            pnOperative.ResumeLayout(false);
            this.ResumeLayout(false);
            pnOperative.PerformLayout();
            this.PerformLayout();
        }
        private void setLayout()
        {
            int gapLine = 20, gapX = 20, gapY=20;
            Size size = new Size();
            int scrW = Screen.PrimaryScreen.Bounds.Width;

            size = bc.MeasureString(lbTitle);
            lbTitle.Location = new System.Drawing.Point((scrW / 2) + (size.Width / 2), gapY);
        }
        private void FrmOrOperativeNote_Load(object sender, EventArgs e)
        {
            //throw new NotImplementedException();
            this.WindowState = FormWindowState.Maximized;
            setLayout();
        }
    }
}
